### PR TITLE
Replace scenecuts-720p set with vimeo-corpus-10s

### PR DESCRIPTION
**Pull request by rzumer**
`scenecuts-720p` was oversized and had a lot of similar content, since clips were cut from only four different videos.
`vimeo-corpus-10s` fulfills the same purpose and more. It is sourced from Creative Commons-licensed videos on Vimeo.
It contains 15 clips trimmed to 10 seconds at timestamps chosen mainly for their complexity. Most of the clips contain at least one scene cut. Content includes 2D and 3D digital animation, screen content, sports, commercials, and misc. live action content. Resolution varies from 720p (if I recall correctly...) to 4K. As a result it is a useful data set for broad testing and performance comparisons, and specifically to evaluate rate control algorithms and keyframe placement/GOP structure decisions.

The set is hosted at https://media.xiph.org/sets/.

### CODE REVIEW

**Comment by rzumer** [comment]
It's been raised that attribution is required for those clips, but most of them are missing that information, so I can't fulfill that requirement and therefore can't distribute that set. Closing.

**Comment by rzumer** [comment]
The set was restored with proper attribution and license information, so I'm reopening this.

**Comment by tdaede** [comment]
Do you need to remove that one video from the list?

**Comment by rzumer** [comment]
What video?

**Pull request merged**
